baseURL: "https://portfolio-website-dvt3.onrender.com/"
languageCode: "en-us"
title: "Kevin Sadi"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: project
      name: Projects
      title: Projects
      url: /projects
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Kevin Sadi Portfolio"
  description: Kevin Sadi's Blog and Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: "#402808"
    secondaryTextColor: "#262626"
    backgroundColor: "#FFFFFF"
    secondaryBackgroundColor: "#B8B8B8"
    primaryColor: "#BFA980"
    secondaryColor: "#faecd9"

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Hi!" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    title: "I'm Kevin Sadi."
    subtitle: "Thanks for visiting"
    content: "Game Engines, Generative AI, Tech Art, Rendering, Audio Programming"
    image: /images/pfp.png
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1TEkX4DwqZ6ohq01WXSLS-E4zCl5QlANQ/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/kevinsadi
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/kevinsadi/
  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/bg_2.JPG"
    content: |-
      I'm currently a student at Georgia Tech. I work with Greg Turk in his generative AI and graphics lab. I'm investigating novel ways to procedurally generate 3D terrain.
      Aside from research, I make games with friends in Unity, UnrealEngine 5, and my own handmade game engine, Kek3D.

      For fun, I play drums with several jazz groups around Atlanta. I also love to play volleyball and/or climb with my friends.


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Generative AI Researcher"
        company: "Georgia Tech - Research"
        #companyUrl: "https://example.com"
        date: "Jan 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          - Worked with Dr. Turk 1:1 on a project in his generative models lab
          - Created generative terrain model based on StyleGAN2
      
      - job: "Computer Graphics Teaching Assistant"
        company: "Georgia Tech - Teaching"
        #companyUrl: "https://example.com"
        date: "Aug 2022 - December 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Provided 1:1 lessons on real-time rendering and physically-based rendering concepts to 250+ students.
          - Worked with other 6 TAs to create materials for lecture and projects, based on ”Fundamentals of Graphics Programming”.
          - Taught content pertaining to graphics pipeline (projection, rasterization, shading/shadows, triangle adjacency) and animation.
      
      - job: "Software Engineering Intern"
        company: "Toast"
        companyUrl: "https://example.com"
        date: "June 2022 - Aug 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          - Collaborated on full-stack tickets across several teams in E-commerce, completing several high priority tickets per sprint.
          - Implemented new end-to-end search functionality using Magento, GraphQL, and React (∼10-13k unique visitors/week).
          - Launched testing tool to compare analytics on two live versions of Toast Shop, increasing Shop Purchase Conversion by 1.41%.
          - Produced logic for aggregating order receipts on major Kotlin service to automate tax filing, included integration and unit testing.

      - job: "Software Engineering Intern"
        company: "NCR Corporation"
        companyUrl: "https://example.com"
        date: "May 2021 - Aug 2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Created NCR’s top priority diagnostic tool for the self checkout Kubernetes back-end managing 7 core micro-services.
          - Completed full stack application still being used by 100+ Self Checkout Engineers, deployed on Walmart cash registers.
          - Developed React Web App through back and forth design work with User Experience (UX) team in Figma.
          - Implemented NodeJS endpoints for automatic JIRA ticket creation.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters of Computer Science"
        school:
          name: "Georgia Institute of Technology, Graphics Specialization"
          #url: "https://example.org"
        date: "Expected Spring 2024"
        GPA: "4.0/4.0"
        content: |-
          Extracurricular Activities
            - Video Game Development
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Georgia Institute of Technology, Media and Intelligence Specialization"
          #url: "https://example.org"
        date: "Expected Spring 2023"
        GPA: "3.86/4.0"
        content: |-
          Extracurricular Activities
            - Video Game Development Club
            - Computer Graphics Teaching Assistant
            - Generative AI research
            - President of Baha'i Club
            - Jazz Band (Big Band and Combo)
        #featuredLink:
        #  enable: true
        #  name: "My academic record"
        #  url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: HackGT7 Facebook Hackathon Winner
        content: PicselAR gives users a way to pixelate their background through various means (e.g., hand gesture/slider, distance to a virtual object, and audio level). Built using SparkAR..
        url: https://github.com/ArmaanLala/PicselAR
      - title: Displayed Art Installation (Project Lead)
        content: Installed interactive art installation in Georgia Tech Center for the performing arts for a month. Involved Mediapipe for hand detection, Unity for effects, Arduino for mechatronics, and Max8 for audio.
        url: "https://www.youtube.com/watch?v=gC2FGTFGS2c&t=269s"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: SpeakEasy
        content: Narrative rhythm game fleshed out with dynamic audio, shaders, and a good time.
        image: /images/projects/speakeasy.png
        featured:
          name: Demo
          link: https://captainturnip.itch.io/speakeasy
        badges:
          - "Unity"
          - "FMOD"
          - "HLSL"
        #links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/hugo-profile


      - title: Kek3D
        content: Handmade 3D game engine that supports transformations, forward rendering, deferred rendering.
        image: /images/projects/Logo12-29-2022.png
        featured:
          name: Code
          link: https://github.com/kevinsadi/kek3d
        badges:
          - "C++"
          - "OpenGL"
        links:
          - icon: fab fa-github
            url: https://github.com/kevinsadi/kek3d

      - title: StyleTerrain
        content: Robust procedural generation of terrain that allows robust mixing of different styles of terrain. 
        image: /images/projects/exportslopelargermax.png
        featured:
          name: Code
          link: https://github.com/kevinsadi/StyleTerrain
        badges:
          - "PyTorch"
          - "StyleGAN2"
        links:
          - icon: fab fa-github
            url: https://github.com/kevinsadi/StyleTerrain


  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/kevinsadi
      linkedin: https://linkedin.com/kevinsadi

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
